GET http://localhost:8080/member/member/count
Accept: application/json

token: 123


> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("token", response.body.content.token);
%}

###

